### ISSUE TITLE
Can't finish setup

### ISSUE THREAD

**Issue by kyanny** [motemen/chrome-GitHub-Issue-Badges#12]
Hello @motemen,

I can't finish setup of this extension.
There's no way to input access token.

<img width="954" alt="screen shot 2017-11-02 at 18 50 05" src="https://user-images.githubusercontent.com/10515/32319922-7511ec5c-bfff-11e7-9292-c4d7d80959b1.png">

I installed v2.5.0 from Chrome webstore. Chrome version is Version 61.0.3163.100 (Official Build) (64-bit) (macOS Sierra).

Could you give me some more instructions?
Thank you!

**Comment by motemen** [comment]
Oh 😞  @yashigani can you look into this?

**Comment by yashigani** [comment]
@kyanny 
I found a miss in init script and fixed it in #13. Please reinstall next version or type this script in your console. Thanks!

``` js
localStorage.setItem('origins', '[{"origin":"https://github.com","apiRoot":"https://api.github.com","token":"","status":0}]');
document.location.reload();
```

**Comment by motemen** [comment]
@yashigani Thanks! Merged with one commit added. (Should have request your review...)

@kyanny Just uploaded v2.5.1 to the store that shoud fix this problem. If not, reopen this issue or create new one. Thank you for letting us know.

**Comment by kyanny** [comment]
@motemen @yashigani 
Thank you for your hard work and sorry to late reply.
I can't get latest version (v2.5.1) of the extension from the store.
Could you check if the latest version was really published? Thanks!

<img width="1440" alt="screen_shot_2017-12-04_at_14_08_06" src="https://user-images.githubusercontent.com/10515/33537053-d025e2ea-d8fc-11e7-9ae0-aaeebb3a3cc1.png">

**Comment by motemen** [comment]
Sorry the extensions were in draft yet! Just made them public so please check them out.

**Comment by kyanny** [comment]
@motemen 
I can get v2.5.1 from the store. Thanks!
